[build]
base = "theaterFront"
command = "npm ci && npm run build"
publish = "dist/theater-front/browser"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
