[build]
base = "theaterFront"
command = "npm ci && npm run build"
publish = "dist/theater-front/browser"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/api/*"
to = "https://theatre-production-eb2c.up.railway.app/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200